enhance setup script with username option and improved error handling

diff --git a/01-setup-rootfs-and-bootloader b/01-setup-rootfs-and-bootloader
--- a/01-setup-rootfs-and-bootloader
+++ b/01-setup-rootfs-and-bootloader
@@ -2,21 +2,57 @@
 
 set -eu
 
+show_help() {
+    echo "Usage: $0 [options]"
+    echo "Options:"
+    echo "  --username <USERNAME> Specify the username"
+    echo "  --help                Show this help message"
+}
+
+# get option --username "username"
+USERNAME=""
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+    --username)
+        [[ -z ${2:-} ]] && (echo "Error: Argument required for $1"; show_help; exit 1)
+        USERNAME="$2"
+        shift 2
+        ;;
+    *)
+        echo "Unknown option: $1"
+        show_help
+        exit 1
+        ;;
+    esac
+done
+
+if [[ -z "${USERNAME:-}" ]]; then
+    echo "Error: --username is required"
+    show_help
+    exit 1
+fi
+echo "set root password"
+passwd # root password
+# setup user
+useradd -m -g users -G wheel -s /bin/bash "$USERNAME"
+echo "set ${USERNAME} password"
+passwd "$USERNAME"
+
 REGION=ASIA
 CITY=Tokyo
 HOST=arch
 ln -sf /usr/share/zoneinfo/${REGION}/${CITY}
 hwclock --systohc
 
-echo -e "en_US.UTF-8 UTF-8\nja_JP.UTF-8 UTF8" >> /etc/locale.gen
+echo -e "en_US.UTF-8 UTF-8\nja_JP.UTF-8 UTF8" >>/etc/locale.gen
 locale-gen
-echo "LANG=en_US.UTF-8" > /etc/locale.conf
+echo "LANG=en_US.UTF-8" >/etc/locale.conf
 
-echo "${HOST}" > /etc/hostname
+echo "${HOST}" >/etc/hostname
 
 # bootloader
 pacman -S grub os-prober efibootmgr
-echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
+echo "GRUB_DISABLE_OS_PROBER=false" >>/etc/default/grub
 grub-install --targe=x86_64-efi --efi-directory=/boot --bootloader-id=grub
 grub-mkconfig -o /boot/grub/grub.cfg
 
@@ -28,9 +64,7 @@ systemctl enable dhcpcd@${NIC}.service
 
 # doas
 pacman -S doas
-echo "permit persist :wheel" >> /etc/doas.conf
+echo "permit persist :wheel" >>/etc/doas.conf
 chmod 0600 /etc/doas.conf
 
-passwd
-echo "reboot and remove install disk"
-exit
+echo "exit from chroot env, reboot and remove install disk"
